services:
  - type: web
    name: greenlands-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        value: your_mongodb_atlas_connection_string
      - key: JWT_SECRET
        value: your_secure_jwt_secret
      - key: CLIENT_URL
        value: https://your-vercel-app-url.vercel.app